# Base rules from the Flutter team.
include: package:flutter_lints/flutter.yaml

analyzer:
  # Make type inference and generics stricter (helps catch bugs early).
  language:
    strict-casts: true
    strict-inference: true
    strict-raw-types: true

  # Don't analyze generated files or build outputs.
  exclude:
    - "**/*.g.dart"
    - "**/*.freezed.dart"
    - "**/*.gen.dart"
    - "build/**"
    - ".dart_tool/**"
    - "android/**"
    - "ios/**"

  # Elevate some diagnostics to errors/warnings for better discipline.
  errors:
    missing_required_param: error
    missing_return: error
    parameter_assignments: error
    invalid_use_of_visible_for_testing_member: error
    depend_on_referenced_packages: error
    unnecessary_import: warning
    unnecessary_nullable_for_final_variable_declarations: warning

linter:
  rules:
    # Imports & organization
    always_use_package_imports: true      # Use 'package:ikra/...' instead of relative imports.
    directives_ordering: true             # Group imports: dart, package, project; and sort.
    sort_pub_dependencies: true           # Keep pubspec dependencies alphabetically sorted.

    # APIs & null-safety hygiene
    avoid_dynamic_calls: true
    no_runtimeType_toString: true
    avoid_redundant_argument_values: true

    # Prefer immutability where sensible
    prefer_final_fields: true
    prefer_final_locals: true
    prefer_final_in_for_each: true

    # Flutter style & consistency
    use_key_in_widget_constructors: true
    use_super_parameters: true
    prefer_const_constructors: true
    prefer_const_declarations: true
    prefer_const_literals_to_create_immutables: true
    sort_child_properties_last: true
    sized_box_for_whitespace: true
    avoid_unnecessary_containers: true
    require_trailing_commas: true
    prefer_single_quotes: true
    flutter_style_todos: true

    # Async / streams hygiene (helps memory-leak patterns)
    cancel_subscriptions: true
    close_sinks: true

    # Logging
    avoid_print: true                     # Use a logger or debugPrint for temporary logs.
