name: ikra
description: Ikra - Offline/Online Qur'an App (Hive + BLoC)

environment:
  sdk: ">=3.3.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter

  # State management
  flutter_bloc: ^8.1.4
  equatable: ^2.0.5

  # Local database
  hive: ^2.2.3
  hive_flutter: ^1.1.0

  # (Optional) JSON helpers for future online API integrations
  json_annotation: ^4.9.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  build_runner: ^2.4.12
  hive_generator: ^2.0.1
  json_serializable: ^6.7.1

flutter:
  uses-material-design: true

  # Put your JSON file here: assets/quran/quran.json
  assets:
    - assets/quran/quran.json
