name: ikra
description: Ikra Quran app
publish_to: "none"
version: 0.1.0+1

environment:
  sdk: ">=3.4.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter

  # State & DI
  flutter_bloc: ^8.1.6
  equatable: ^2.0.5
  get_it: ^7.6.7

  # Data & network
  http: ^1.2.1
  hive: ^2.2.3
  hive_flutter: ^1.1.0

  # Features
  geolocator: ^14.0.2
  just_audio: ^0.9.39
  connectivity_plus: ^6.0.3

  # UI
  cupertino_icons: ^1.0.6

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.1
  build_runner: ^2.4.8
  hive_generator: ^2.0.1

flutter:
  uses-material-design: true

  assets:
    - assets/quran/quran.json

  fonts:
    - family: AmiriQuran
      fonts:
        - asset: assets/fonts/amiri/AmiriQuran-Regular.ttf
          weight: 400
    - family: KFGQPCUthmanicHafs
      fonts:
        - asset: assets/fonts/kfgqpc/KFGQPCUthmanicHafs-Regular.otf
          weight: 400